### ISSUE TITLE
Nova Artisan File Support for php 8.1

### ISSUE THREAD

**Issue by emadrashadmuhammed** [mostafaznv/nova-larupload#18]
Hey , thanks for such great work any work around to use Nova Artisan File with php 8.1

**Comment by mostafaznv** [comment]
Hi @emadkingslayer,
This package has been implemented on top of PHP 8.2 since day one. Downgrading it to PHP 8.1 would require significant work, and unfortunately, I don’t have enough time to do that right now.

I suggest upgrading your environment to PHP 8.2, as I believe it may not impact your code: https://www.php.net/manual/en/migration82.deprecated.php
